### ISSUE TITLE
Remove/Add a role does not update the local array of the ServerMember RoleIds

### ISSUE THREAD

**Issue by JJiGolem** [FluxpointDev/RevoltSharp#29]
If you do several RemoveRoleAsync (as well as AddRoleAsync) in the same context, then a mess occurs))
Those roles that were deleted before the current deletion are restored. Most likely, the local list of Rolaids is not updated after performing Remove/Add Role Async.

[Video without AddRole method](https://skrinshoter.ru/vS9EyU7F30u)
[Video with AddRole method](https://skrinshoter.ru/vS9gKUdCJkD)

**Comment by JJiGolem** [comment]
This is **RemoveRolesAsync** request
![image](https://github.com/user-attachments/assets/6c5e61e8-8192-4e40-bfa9-a766810d62ba)

After this is **AddRolesAsync** request
![image](https://github.com/user-attachments/assets/cf6cc18d-8d2b-4613-be9a-908496c5a660)

As you can see from the screenshots, previously deleted roles are present in our request. Which means they haven't been removed from **RoleIds**

**Comment by xXBuilderBXx** [comment]
Thanks for reporting usually it should update when a server member update event occurs but will test it out

**Comment by xXBuilderBXx** [comment]
Done a fix in v7.6.3 that will wait on add/remove role requests per-member so it does not go out of sync.
